# Generated by Django 3.2 on 2021-04-23 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Age', models.IntegerField()),
                ('Gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('had_asthma_attack_in_the_last_year', models.CharField(choices=[('no', 'No'), ('yes', 'Yes')], max_length=10)),
                ('smoked_at_least_100_cigarettes_in_life', models.CharField(choices=[('no', 'No'), ('yes', 'Yes')], max_length=10)),
                ('spirometry_measure', models.CharField(max_length=100)),
                ('blood_eosinophilis_count', models.CharField(max_length=200)),
                ('patient_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
