# Generated by Django 3.2 on 2021-04-23 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_name',
            field=models.CharField(max_length=256),
        ),
    ]
